language: php
php:
    - 5.6
    - 7.0
    - hhvm

matrix:
  allow_failures:
    - php: hhvm

  include:
    - php: 5.6
      env: COMPOSER_FLAG=--prefer-lowest
    - php: 5.6
      env: COMPOSER_FLAG=--prefer-stable
    - php: 7.0
      env: COMPOSER_FLAG=--prefer-lowest
    - php: 7.0
      env: COMPOSER_FLAG=--prefer-stable

before_script:
    # Update Composer
    - composer self-update

    # Install Nette Tester
    - composer update --no-interaction --prefer-source $COMPOSER_FLAG

script:
    - vendor/bin/tester -p php -i
    - vendor/bin/tester tests/cases -s -p php

after_failure:
    # Print *.actual content
    - 'for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
